import React, { useState } from 'react';
import { useParams, Navigate } from 'react-router-dom';
import { useData } from '../../context/DataContext';
import { Sparkles, ArrowRight, Loader2, Copy } from 'lucide-react';

export const AppRunner: React.FC = () => {
  const { slug } = useParams<{ slug: string }>();
  const { data } = useData();
  const app = data.aiApps.find(a => a.slug === slug);
  
  const [inputs, setInputs] = useState<Record<string, string>>({});
  const [loading, setLoading] = useState(false);
  const [output, setOutput] = useState<string | null>(null);

  if (!app) return <Navigate to="/" replace />;

  const handleRun = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setOutput(null);

    // Simulate AI Processing
    setTimeout(() => {
      let result = app.promptTemplate;
      Object.keys(inputs).forEach(key => {
        result = result.replace(new RegExp(`{{${key}}}`, 'g'), inputs[key]);
      });
      
      // Add fake AI flavor text
      result = `[AI Generated Output]\n\n${result}\n\n(This is a mock response generated by the ${app.name} tool configuration.)`;
      
      setOutput(result);
      setLoading(false);
    }, 1500);
  };

  return (
    <div className="min-h-screen bg-gray-50 py-12">
      <div className="container mx-auto px-4 max-w-3xl">
         <div className="bg-white rounded-2xl shadow-xl overflow-hidden border border-gray-100">
            {/* Header */}
            <div className="bg-slate-900 p-8 text-white">
               <div className="flex items-center space-x-3 mb-4">
                  <div className="bg-brand-500 p-2 rounded-lg">
                    <Sparkles className="h-6 w-6 text-white" />
                  </div>
                  <h1 className="text-2xl font-bold">{app.name}</h1>
               </div>
               <p className="text-slate-300">{app.description}</p>
            </div>

            <div className="p-8">
               <form onSubmit={handleRun} className="space-y-6">
                  {app.inputs.map(input => (
                    <div key={input.id}>
                       <label className="block text-sm font-medium text-gray-700 mb-2">{input.label}</label>
                       {input.type === 'textarea' ? (
                          <textarea required className="w-full border border-gray-300 rounded-lg p-3 focus:ring-2 focus:ring-brand-500 outline-none" 
                             rows={4}
                             placeholder={input.placeholder}
                             onChange={e => setInputs({...inputs, [input.key]: e.target.value})}
                          />
                       ) : input.type === 'select' ? (
                          <select className="w-full border border-gray-300 rounded-lg p-3 focus:ring-2 focus:ring-brand-500 outline-none"
                             onChange={e => setInputs({...inputs, [input.key]: e.target.value})}
                          >
                             <option value="">Select option...</option>
                             {input.options?.split(',').map(opt => <option key={opt} value={opt}>{opt}</option>)}
                          </select>
                       ) : (
                          <input required type={input.type} className="w-full border border-gray-300 rounded-lg p-3 focus:ring-2 focus:ring-brand-500 outline-none" 
                             placeholder={input.placeholder}
                             onChange={e => setInputs({...inputs, [input.key]: e.target.value})}
                          />
                       )}
                    </div>
                  ))}

                  <button disabled={loading} type="submit" className="w-full py-4 bg-brand-600 hover:bg-brand-700 text-white font-bold rounded-lg transition flex justify-center items-center">
                     {loading ? <Loader2 className="h-5 w-5 animate-spin" /> : <>{app.actionLabel} <ArrowRight className="h-5 w-5 ml-2" /></>}
                  </button>
               </form>

               {output && (
                 <div className="mt-8 pt-8 border-t border-gray-100 animation-fade-in">
                    <div className="flex justify-between items-center mb-4">
                       <h3 className="font-bold text-gray-900">Result</h3>
                       <button onClick={() => navigator.clipboard.writeText(output)} className="text-sm text-brand-600 flex items-center hover:underline">
                          <Copy className="h-4 w-4 mr-1" /> Copy
                       </button>
                    </div>
                    <div className="bg-slate-50 p-6 rounded-xl border border-slate-200 whitespace-pre-wrap font-mono text-sm text-slate-700">
                       {output}
                    </div>
                 </div>
               )}
            </div>
         </div>
      </div>
    </div>
  );
};
